export const SITE_CONFIG = {
  name: "ComparaHogar",
  domain: "https://comparahogar.es",
  tagline: "Comparativas honestas de tecnologia para tu hogar inteligente",
  description: "Comparativas y analisis reales de robots aspiradores, altavoces inteligentes, camaras de seguridad WiFi, iluminacion smart y domotica. Probamos cada producto durante semanas en Alicante, Espana. Guias de compra actualizadas marzo 2026.",
  amazonTag: "digitalconect-21",
  priceDisclaimer: "Precios orientativos actualizados periodicamente. El precio final es el de Amazon.es en el momento de la compra.",
  priceSource: "catalog",
  locale: "es_ES",
  company: "Digital Conect",
};

export const CATEGORIES = [
  { id: "aspiradores", name: "Robots Aspiradores", icon: "\u{1F916}", slug: "robots-aspiradores", color: "#10B981", description: "Comparativas de los mejores robots aspiradores y friegasuelos de 2026. Roborock, Dreame, Xiaomi analizados en Espana.", metaTitle: "Mejores Robots Aspiradores 2026 - Comparativas reales", metaDescription: "Robots aspiradores probados durante semanas. Roborock S8 MaxV, Dreame L10s, Xiaomi X10+. Comparativas honestas." },
  { id: "altavoces", name: "Altavoces Inteligentes", icon: "\u{1F50A}", slug: "altavoces-inteligentes", color: "#F97316", description: "Alexa vs Google Home. Analisis de Echo Dot, Echo Show y Google Nest Hub para tu hogar inteligente.", metaTitle: "Mejores Altavoces Inteligentes 2026 - Alexa vs Google", metaDescription: "Echo Dot, Echo Show 8, Google Nest Hub. Cual elegir segun tu ecosistema." },
  { id: "seguridad", name: "Camaras y Seguridad", icon: "\u{1F4F9}", slug: "camaras-seguridad", color: "#8B5CF6", description: "Camaras de seguridad WiFi probadas en condiciones reales. Sin suscripcion, con vision nocturna, para interior y exterior.", metaTitle: "Mejores Camaras Seguridad WiFi 2026 - Sin Suscripcion", metaDescription: "Tapo C320WS, Ring Indoor, Reolink Argus. Camaras probadas en exterior e interior." },
  { id: "iluminacion", name: "Iluminacion WiFi", icon: "\u{1F4A1}", slug: "iluminacion-wifi", color: "#FBBF24", description: "Bombillas y tiras LED inteligentes. Philips Hue, TP-Link Tapo, IKEA Dirigera comparados.", metaTitle: "Iluminacion Inteligente 2026 - Hue vs Tapo vs IKEA", metaDescription: "Philips Hue vs Tapo L530E. Kit starter, precios, ecosistemas comparados." },
  { id: "enchufes", name: "Enchufes y Sensores", icon: "\u{1F50C}", slug: "enchufes-inteligentes", color: "#F43F5E", description: "Enchufes WiFi con medicion de consumo, sensores de presencia y automatizacion del hogar.", metaTitle: "Enchufes Inteligentes y Sensores 2026 - Guia completa", metaDescription: "Tapo P110, SwitchBot, Aqara FP2. Enchufes y sensores analizados." },
  { id: "climatizacion", name: "Climatizacion Smart", icon: "\u{1F321}", slug: "climatizacion-smart", color: "#06B6D4", description: "Termostatos inteligentes y control de climatizacion. Datos reales de ahorro en calefaccion y aire acondicionado.", metaTitle: "Termostatos Inteligentes 2026 - Ahorro real en calefaccion", metaDescription: "Tado V3+, datos reales de ahorro. Termostatos que se amortizan solos." },
];

export const PRODUCTS = [
  {
    id:1, slug:"roborock-s8-maxv-ultra", name:"Roborock S8 MaxV Ultra",
    category:"aspiradores", rating:4.4, reviews:2822, price:"649,00", oldPrice:"1.099,99",
    badge:"N.1 Calidad", badgeColor:"#10B981", weeklyBest:true,
    image:"https://m.media-amazon.com/images/I/71cihNMRF4L._AC_SL1500_.jpg",
    imageAlt:"Roborock S8 MaxV Ultra robot aspirador con estacion de autovaciado y fregado sonico 2026",
    imageTitle:"Roborock S8 MaxV Ultra - Robot aspirador premium con IA y fregado sonico",
    shortDesc:"El robot aspirador y friegasuelos mas completo del mercado. Navegacion IA con reconocimiento de objetos, fregado sonico VibraRise 3.0 a 4.000 vibraciones por minuto y succion de 10.000Pa. Ideal para pisos grandes de mas de 100m2 con mascotas.",
    longDesc:"Tras tres meses de uso diario en un piso de 120m2, el Roborock S8 MaxV Ultra se ha ganado el primer puesto. Su camara IA reconoce juguetes, cables y hasta los cuencos del perro. El fregado sonico es otro nivel comparado con los sistemas de presion: elimina manchas secas de cafe que otros robots ni tocan. La estacion base lava y seca las mopas con agua caliente, vacia el deposito automaticamente y lleva un dispensador de detergente para tres meses. El unico pero real es su tamano, la estacion necesita 40cm de espacio libre.",
    pros:["Navegacion LiDAR + camara IA reconoce 73 tipos de objetos","Fregado sonico VibraRise 3.0 a 4.000 vibraciones/min","Autovaciado + autolimpieza de mopa con agua caliente","Succion 10.000Pa para alfombras gruesas","Brazo FlexiArm para esquinas"],
    cons:["Precio alto para presupuestos ajustados","Estacion base ocupa bastante espacio","App Roborock requiere cuenta"],
    verdict:"El robot aspirador y friegasuelos mas completo de 2026. Si tu presupuesto lo permite, no vas a necesitar otro en muchos anos. La combinacion de navegacion IA, fregado sonico y autovaciado con agua caliente deja atras a todo lo demas.",
    amazonUrl:"https://www.amazon.es/dp/B0CRV7F37B?tag=digitalconect-21",
    metaTitle:"Roborock S8 MaxV Ultra: Analisis real tras 3 meses de uso (2026)",
    metaDescription:"Opinion honesta del Roborock S8 MaxV Ultra tras 3 meses. Navegacion IA, fregado sonico 4000 vibraciones, autovaciado. El mejor robot aspirador 2026 en Espana desde 649€.",
  },
  {
    id:2, slug:"dreame-l10s-ultra-gen2", name:"Dreame L10s Ultra Gen 2",
    category:"aspiradores", rating:4.3, reviews:3245, price:"373,00", oldPrice:"499,99",
    badge:"Mejor Precio/Calidad", badgeColor:"#F97316", weeklyBest:true,
    image:"https://m.media-amazon.com/images/I/61gvoVh3u-L._AC_SL1200_.jpg",
    imageAlt:"Dreame L10s Ultra Gen 2 robot aspirador con base autovaciado para hogares con mascotas",
    imageTitle:"Dreame L10s Ultra Gen 2 - Robot aspirador con mejor relacion calidad-precio 2026",
    shortDesc:"Succion de 5.300Pa pensada para hogares con mascotas. La base autovaciado aguanta 60 dias sin mantenimiento y el mapeo laser completa 100m2 en 8 minutos. El rival directo del Roborock a precio mas accesible.",
    longDesc:"En hogares con perro o gato, el Dreame L10s Ultra Gen 2 marca diferencia. Los 5.300Pa de succion arrancan pelo incrustado en alfombras que robots de 4.000Pa dejan a medias. La base tiene autovaciado para 60 dias, un lujo que a este precio no ofrece nadie mas. El mapeo laser tarda 8 minutos en cubrir 100m2 y genera zonas que puedes editar. El fregado funciona por presion, eficaz con polvo pero no quita manchas secas como el sonico del Roborock. La app de Dreame ha mejorado mucho en el ultimo ano, aunque sigue algo mas lenta que la de Roborock.",
    pros:["Succion 5.300Pa arranca pelo de mascota incrustado","Base autovaciado dura 60 dias sin vaciar","Mapeo laser rapido en 8 minutos","Precio competitivo con base completa"],
    cons:["Fregado por presion menos eficaz que sonico","App Dreame algo lenta en responder"],
    verdict:"La mejor alternativa al Roborock S8 MaxV Ultra a mitad de precio. Si tienes mascotas y no quieres gastarte 900€, este es tu robot. El autovaciado de 60 dias es un lujo a este precio.",
    amazonUrl:"https://www.amazon.es/dp/B0DCVYS9FQ?tag=digitalconect-21",
    metaTitle:"Dreame L10s Ultra Gen 2: Opinion real con mascotas en casa (2026)",
    metaDescription:"Analisis del Dreame L10s Ultra Gen 2. Succion 5300Pa, autovaciado 60 dias, ideal para mascotas. El mejor robot aspirador calidad-precio 2026 desde 373€.",
  },
  {
    id:3, slug:"xiaomi-robot-x10-plus", name:"Xiaomi Robot X10+",
    category:"aspiradores", rating:4.3, reviews:1580, price:"329,99", oldPrice:"449,99",
    badge:"Gama Media Top", badgeColor:"#F97316", weeklyBest:false,
    image:"https://m.media-amazon.com/images/I/61OxR88NJIL._AC_SL1500_.jpg",
    imageAlt:"Xiaomi Robot X10 Plus robot aspirador con estacion autovaciado y fregado vibratorio",
    imageTitle:"Xiaomi X10+ - Robot aspirador gama media con ecosistema Xiaomi Home",
    shortDesc:"Robot con base autovaciado y fregado vibratorio dentro del ecosistema Xiaomi. Si ya usas productos de la marca, la integracion con Xiaomi Home es perfecta y el precio muy competitivo.",
    longDesc:"El Xiaomi X10+ es la puerta de gama media para quien ya tiene otros productos Xiaomi. La base autovaciado viene incluida, algo que competidores como Roomba cobran aparte. El fregado vibratorio funciona bien para polvo y suciedad ligera. La app Xiaomi Home es estable y permite crear automatizaciones con otros dispositivos de la marca. La succion de 4.000Pa es correcta para suelos duros pero se queda corta en alfombras gruesas. La deteccion de objetos es basica comparada con el Roborock o Dreame.",
    pros:["Base autovaciado incluida en el precio","Fregado vibratorio para polvo diario","App Xiaomi Home estable e integrada","Precio competitivo de 379€"],
    cons:["Succion 4.000Pa justa para alfombras gruesas","Deteccion de objetos basica sin camara IA"],
    verdict:"Buena opcion si ya tienes productos Xiaomi en casa. La integracion es su punto fuerte. Para suelos duros y pisos de tamano medio cumple sin problemas.",
    amazonUrl:"https://www.amazon.es/dp/B0B1N5HB3C?tag=digitalconect-21",
    metaTitle:"Xiaomi Robot X10+: Merece la pena en 2026? Opinion real",
    metaDescription:"Analisis del Xiaomi X10+. Autovaciado, fregado vibratorio, ecosistema Xiaomi Home. Robot aspirador gama media desde 329€.",
  },
  {
    id:4, slug:"echo-show-8-2024", name:"Amazon Echo Show 8 (2024)",
    category:"altavoces", rating:4.5, reviews:4521, price:"154,99", oldPrice:"169,99",
    badge:"Centro del Hogar", badgeColor:"#8B5CF6", weeklyBest:true,
    image:"https://m.media-amazon.com/images/I/71FsBVrPOtL._AC_SL1000_.jpg",
    imageAlt:"Amazon Echo Show 8 2024 pantalla inteligente con Alexa para control del hogar",
    imageTitle:"Echo Show 8 (2024) - Pantalla inteligente Alexa con videollamadas y domotica",
    shortDesc:"Pantalla tactil de 8 pulgadas con Alexa, camara de 13MP para videollamadas y hub Zigbee integrado. El centro de control perfecto para manejar todos tus dispositivos inteligentes desde un solo sitio.",
    longDesc:"El Echo Show 8 ha pasado de ser un reloj bonito a convertirse en el cerebro de la casa. La pantalla de 8 pulgadas es suficiente para ver recetas, las camaras de seguridad y hacer videollamadas con calidad. Lo que lo distingue es el hub Zigbee integrado: conecta bombillas Hue, sensores y enchufes sin necesitar un bridge extra. El sonido espacial sorprende para su tamano. Como contras, el ecosistema es Amazon y punto, y de vez en cuando aparecen sugerencias de compra que molestan un poco.",
    pros:["Pantalla tactil 8 pulgadas + camara 13MP","Sonido espacial envolvente para su tamano","Hub Zigbee integrado para domotica directa","Videollamadas, musica, recetas, camaras"],
    cons:["Ecosistema cerrado Amazon exclusivamente","Publicidad y sugerencias de compra ocasionales"],
    verdict:"La pantalla inteligente mas completa como centro de control del hogar. Si usas Alexa, es el dispositivo que une todo.",
    amazonUrl:"https://www.amazon.es/dp/B0BLS3Y632?tag=digitalconect-21",
    metaTitle:"Echo Show 8 (2024): El centro de control del hogar inteligente",
    metaDescription:"Analisis del Echo Show 8. Pantalla 8 pulgadas, hub Zigbee, videollamadas 13MP. El mejor dispositivo Alexa para domotica por 149€.",
  },
  {
    id:5, slug:"echo-dot-5gen", name:"Amazon Echo Dot 5a Gen",
    category:"altavoces", rating:4.7, reviews:12840, price:"54,99", oldPrice:"64,99",
    badge:"Mas Vendido", badgeColor:"#F43F5E", weeklyBest:true,
    image:"https://m.media-amazon.com/images/I/71xoR4A7xvL._AC_SL1000_.jpg",
    imageAlt:"Amazon Echo Dot 5 generacion altavoz inteligente Alexa compacto en color negro",
    imageTitle:"Echo Dot 5a Gen - Altavoz Alexa mas vendido en Espana 2026",
    shortDesc:"El altavoz inteligente mas vendido en Espana. Tienes acceso completo a Alexa con sensor de temperatura incluido. El punto de entrada perfecto a la domotica.",
    longDesc:"Doce millones de valoraciones no mienten. El Echo Dot 5a generacion cuesta menos que una pizza para dos y te da acceso a todo Alexa: controlar luces, enchufes, poner musica, preguntar el tiempo, crear listas de la compra por voz. El sonido ha mejorado respecto al Dot 4, con graves mas presentes aunque sin milagros en un cuerpo tan compacto. El sensor de temperatura es un bonus util para automatizaciones. En ofertas frecuentes baja a menos de 30€, un chollo.",
    pros:["Menos de 30€ en oferta frecuente","Sonido mejorado respecto a generacion anterior","Sensor de temperatura integrado","Acceso completo a Alexa y miles de skills"],
    cons:["Graves escasos por el tamano compacto","Sin pantalla para informacion visual"],
    verdict:"La puerta de entrada al hogar inteligente. A este precio es imposible equivocarse. Compralo, prueba Alexa y decide si quieres expandir.",
    amazonUrl:"https://www.amazon.es/dp/B09B8X9RGM?tag=digitalconect-21",
    metaTitle:"Echo Dot 5a Gen: Por que es el altavoz mas vendido de Espana (2026)",
    metaDescription:"Echo Dot 5 por 29€. Sensor temperatura, Alexa completo, sonido mejorado. El altavoz inteligente que mas se vende en Espana. Baja a 30€ en ofertas frecuentes.",
  },
  {
    id:6, slug:"google-nest-hub-2gen", name:"Google Nest Hub 2a Gen",
    category:"altavoces", rating:4.4, reviews:3210, price:"89,99", oldPrice:"109,99",
    badge:"Mejor Google", badgeColor:"#4285F4", weeklyBest:false,
    image:"https://m.media-amazon.com/images/I/61FTvkBGI7L._AC_SL1500_.jpg",
    imageAlt:"Google Nest Hub 2 generacion pantalla inteligente con seguimiento de sueno",
    imageTitle:"Google Nest Hub 2 - Pantalla inteligente Google Assistant con monitor de sueno",
    shortDesc:"Pantalla de 7 pulgadas con Google Assistant y seguimiento de sueno sin contacto mediante radar Soli. La alternativa a Echo Show si prefieres el ecosistema Google y Android.",
    longDesc:"El Nest Hub 2 tiene una ventaja que ninguna pantalla Amazon ofrece: seguimiento de sueno sin ponerte nada encima. El radar Soli detecta tu respiracion y movimiento durante la noche. Como marco de fotos con Google Photos es fantastico, sincroniza tus albumes favoritos automaticamente. El sonido es limpio y claro. Lo que le falta: no tiene camara, asi que nada de videollamadas. Y el catadogo de skills de Google sigue por detras del de Alexa para domotica.",
    pros:["Monitor de sueno sin contacto con radar Soli","Google Photos como marco digital automatico","Sonido claro y natural","Integracion nativa con Android"],
    cons:["Sin camara para videollamadas","Menos skills y dispositivos compatibles que Alexa"],
    verdict:"Si tu movil es Android y prefieres Google a Amazon, esta pantalla es la correcta. El seguimiento de sueno es un diferencial que Alexa no tiene.",
    amazonUrl:"https://www.amazon.es/dp/B0BCTYDFHM?tag=digitalconect-21",
    metaTitle:"Google Nest Hub 2: La alternativa real al Echo Show (2026)",
    metaDescription:"Nest Hub 2 con seguimiento de sueno por radar, Google Photos, pantalla 7 pulgadas. La mejor pantalla Google por 79€.",
  },
  {
    id:7, slug:"tapo-c320ws", name:"TP-Link Tapo C320WS",
    category:"seguridad", rating:4.4, reviews:7230, price:"39,99", oldPrice:"49,99",
    badge:"Mejor Exterior", badgeColor:"#10B981", weeklyBest:true,
    image:"https://m.media-amazon.com/images/I/61q2h25gFcL._AC_SL1500_.jpg",
    imageAlt:"TP-Link Tapo C320WS camara seguridad exterior WiFi 2K vision nocturna color",
    imageTitle:"Tapo C320WS - Camara seguridad exterior 2K sin suscripcion mensual",
    shortDesc:"Camara exterior 2K con vision nocturna a color real, resistencia IP66 y grabacion en MicroSD sin pagar suscripcion. La camara de seguridad exterior mas vendida de Amazon.es por menos de 40 euros.",
    longDesc:"Siete mil valoraciones en Amazon y una nota de 4.4 no son casualidad. La Tapo C320WS graba en 2K real con vision nocturna a color gracias a su foco integrado. Resiste lluvia y sol directo con certificacion IP66. Lo mejor: graba en tarjeta MicroSD, cero euros al mes de suscripcion. La deteccion de movimiento distingue personas de animales, asi que no recibes 40 notificaciones al dia por gatos callejeros. El audio bidireccional permite hablar con quien este en la puerta. Solo necesita cable de alimentacion y WiFi 2.4GHz.",
    pros:["Resolucion 2K real con vision nocturna a color","IP66 resistente a lluvia y temperaturas extremas","MicroSD local sin suscripcion mensual","Deteccion inteligente persona vs animal"],
    cons:["Solo compatible con WiFi 2.4GHz","Necesita cable de alimentacion permanente"],
    verdict:"Por 40€ no hay nada mejor para vigilar la entrada, el jardin o el garaje. Grabacion 2K sin cuotas mensuales. Es la camara exterior mas vendida por algo.",
    amazonUrl:"https://www.amazon.es/dp/B09JFK81S7?tag=digitalconect-21",
    metaTitle:"Tapo C320WS: La mejor camara exterior barata sin suscripcion (2026)",
    metaDescription:"Camara exterior Tapo C320WS por 39€. 2K, vision nocturna color, IP66, MicroSD. Sin pagar suscripcion mensual. 7000+ opiniones.",
  },
  {
    id:8, slug:"ring-indoor-cam", name:"Ring Indoor Cam 2a Gen",
    category:"seguridad", rating:4.3, reviews:5410, price:"59,99", oldPrice:"79,99",
    badge:"Mejor Interior", badgeColor:"#8B5CF6", weeklyBest:false,
    image:"https://m.media-amazon.com/images/I/51LhOPfBZyL._AC_SL1000_.jpg",
    imageAlt:"Ring Indoor Cam 2 generacion camara interior compacta compatible Alexa",
    imageTitle:"Ring Indoor Cam 2a Gen - Camara interior con Alexa integrada",
    shortDesc:"La camara de interior mas compacta con integracion nativa Alexa. Audio bidireccional, 1080p y notificaciones directas en tu Echo Show. Ideal para vigilar mascotas o la habitacion del bebe.",
    longDesc:"Si tienes un Echo Show o un Echo Dot, la Ring Indoor Cam encaja como anillo al dedo. Di 'Alexa, ensenameame la camara del salon' y la ves al instante. El tamano es diminuto, cabe en cualquier estanteria. El audio bidireccional te permite hablar con quien este en casa. La pega: para guardar grabaciones necesitas Ring Protect, que cuesta 3,99€ al mes. Sin suscripcion solo puedes ver en directo.",
    pros:["Audio bidireccional de calidad","Integracion Alexa nativa inmediata","Tamano compacto y discreto","Notificaciones en Echo Show"],
    cons:["Suscripcion Ring Protect para grabaciones","Solo 1080p cuando la competencia va a 2K"],
    verdict:"Si tienes Echo, la Ring Indoor Cam es la que mejor se integra. Para vigilar mascotas o la habitacion del bebe funciona perfecto. Decide si pagas los 3,99€ de suscripcion.",
    amazonUrl:"https://www.amazon.es/dp/B0BFJNKJNZ?tag=digitalconect-21",
    metaTitle:"Ring Indoor Cam 2a Gen: Merece pagar la suscripcion? Opinion real",
    metaDescription:"Ring Indoor Cam 2 por 59€. Audio bidireccional, Alexa nativa. Necesita Ring Protect? Analisis honesto.",
  },
  {
    id:9, slug:"reolink-argus-4-pro", name:"Reolink Argus 4 Pro",
    category:"seguridad", rating:4.5, reviews:1540, price:"129,99", oldPrice:"159,99",
    badge:"Sin Cables", badgeColor:"#10B981", weeklyBest:false,
    image:"https://m.media-amazon.com/images/I/61kJ6yFdsCL._AC_SL1500_.jpg",
    imageAlt:"Reolink Argus 4 Pro camara seguridad 4K solar inalambrica sin cables",
    imageTitle:"Reolink Argus 4 Pro - Camara 4K solar 100% inalambrica",
    shortDesc:"Camara de seguridad 4K totalmente inalambrica con panel solar incluido y WiFi 6 de doble banda. Sin cables, sin suscripcion. Ideal para zonas donde no llega el enchufe.",
    longDesc:"La Reolink Argus 4 Pro resuelve el mayor problema de las camaras: el cable. Es 100% inalambrica con panel solar incluido que la mantiene cargada todo el ano. La calidad 4K es real, puedes leer matriculas a 10 metros. WiFi 6 doble banda significa que la conexion es estable incluso lejos del router. Graba en MicroSD sin suscripcion. La pega: la app solo esta en ingles y el precio de 130€ es alto comparado con la Tapo.",
    pros:["Resolucion 4K ultra HD real","Panel solar incluido en el precio","WiFi 6 doble banda estable a distancia","Grabacion MicroSD sin suscripcion"],
    cons:["Precio elevado respecto a alternativas con cable","Aplicacion solo disponible en ingles"],
    verdict:"La mejor camara sin cables del mercado. Si necesitas vigilar una zona sin enchufe cercano, es la unica opcion seria con 4K y panel solar incluido.",
    amazonUrl:"https://www.amazon.es/dp/B0BXFQ3Z8D?tag=digitalconect-21",
    metaTitle:"Reolink Argus 4 Pro: Camara 4K solar sin cables - Opinion 2026",
    metaDescription:"Reolink Argus 4 Pro por 129€. 4K real, panel solar, WiFi 6, sin cables ni suscripcion. La mejor camara inalambrica.",
  },
  {
    id:10, slug:"philips-hue-starter", name:"Philips Hue Starter Kit E27",
    category:"iluminacion", rating:4.7, reviews:3412, price:"89,99", oldPrice:"119,99",
    badge:"Imprescindible", badgeColor:"#FBBF24", weeklyBest:true,
    image:"https://m.media-amazon.com/images/I/61DUO0NqyyL._AC_SL1500_.jpg",
    imageAlt:"Philips Hue Starter Kit E27 bombillas inteligentes 16 millones colores con Bridge",
    imageTitle:"Philips Hue Starter Kit - Iluminacion inteligente premium con Bridge incluido",
    shortDesc:"El kit de inicio de iluminacion inteligente por excelencia. 3 bombillas E27 con 16 millones de colores y Bridge incluido. Compatible con Alexa, Google y Apple HomeKit simultaneamente.",
    longDesc:"Philips Hue lleva anos siendo la referencia en iluminacion inteligente y hay razones solidas para ello. El kit incluye 3 bombillas E27 y el Bridge, que conecta hasta 50 bombillas via Zigbee. La triple compatibilidad con Alexa, Google y HomeKit significa que no te atas a ningun ecosistema. Los colores son fieles y la transicion entre tonos es suave, sin parpadeos. Las escenas predefinidas son muy buenas. El precio por bombilla es alto comparado con Tapo, pero la fiabilidad y el ecosistema justifican la diferencia si puedes permitirtelo.",
    pros:["16 millones de colores fieles y sin parpadeos","Bridge Zigbee incluido para hasta 50 bombillas","Compatible Alexa + Google + Apple HomeKit","Ecosistema maduro con cientos de escenas"],
    cons:["Bombillas adicionales cuestan 25-40€ cada una","Bridge obligatorio, sin WiFi directo"],
    verdict:"El ecosistema de iluminacion inteligente mas fiable del mercado. El kit starter es la mejor forma de empezar. Si puedes asumir el precio, no te arrepientes.",
    amazonUrl:"https://www.amazon.es/dp/B01LZ8QYPI?tag=digitalconect-21",
    metaTitle:"Philips Hue Starter Kit E27: Merece la pena en 2026? Guia completa",
    metaDescription:"Philips Hue Starter Kit por 89€. Bridge + 3 bombillas E27, 16M colores, Alexa + Google + HomeKit. Analisis y guia.",
  },
  {
    id:11, slug:"tapo-l530e-pack2", name:"TP-Link Tapo L530E x2",
    category:"iluminacion", rating:4.3, reviews:6140, price:"19,99", oldPrice:"27,99",
    badge:"Mas Barata", badgeColor:"#F43F5E", weeklyBest:false,
    image:"https://m.media-amazon.com/images/I/51WkhtCvLpL._AC_SL1500_.jpg",
    imageAlt:"TP-Link Tapo L530E pack 2 bombillas WiFi multicolor inteligentes sin hub",
    imageTitle:"Tapo L530E Pack 2 - Bombillas WiFi mas baratas con 16 millones de colores",
    shortDesc:"Dos bombillas WiFi multicolor por 20 euros. Sin hub, sin bridge, se conectan directas al router. La forma mas barata de probar iluminacion inteligente en casa.",
    longDesc:"A 10€ la bombilla, las Tapo L530E son la forma mas accesible de probar iluminacion inteligente. Se conectan directo al WiFi sin necesitar ningun hub o bridge. La instalacion tarda 3 minutos: enroscas, abres la app Tapo, conectas y listo. Los 16 millones de colores estan ahi, aunque los tonos pastel y blancos calidos son menos fieles que en Philips Hue. Para lamparas de salon, dormitorio o crear ambiente, cumplen de sobra. Si quieres probar antes de invertir en Hue, es la compra perfecta.",
    pros:["Sin hub ni bridge, WiFi directo","16 millones de colores por 10€ la bombilla","Instalacion en 3 minutos","Compatible Alexa y Google Home"],
    cons:["Solo WiFi 2.4GHz","Colores menos fieles que Philips Hue"],
    verdict:"La opcion mas barata para entrar en iluminacion inteligente. A 10€ por bombilla no hay riesgo. Prueba, y si te gusta inviertes en Hue.",
    amazonUrl:"https://www.amazon.es/dp/B07V47FMJM?tag=digitalconect-21",
    metaTitle:"Tapo L530E Pack 2: Bombillas WiFi por 10€ cada una - Opinion 2026",
    metaDescription:"2 bombillas Tapo L530E por 19€. Sin hub, WiFi directo, 16M colores. La alternativa mas barata a Philips Hue.",
  },
  {
    id:12, slug:"tapo-p110-pack4", name:"TP-Link Tapo P110 x4",
    category:"enchufes", rating:4.4, reviews:8920, price:"39,99", oldPrice:"54,99",
    badge:"Pack Ahorro", badgeColor:"#F43F5E", weeklyBest:true,
    image:"https://m.media-amazon.com/images/I/51k2064fHRL._AC_SL1000_.jpg",
    imageAlt:"TP-Link Tapo P110 pack 4 enchufes inteligentes WiFi con medicion consumo electrico",
    imageTitle:"Tapo P110 Pack 4 - Enchufes WiFi con monitor de consumo electrico",
    shortDesc:"Pack de 4 enchufes inteligentes con medicion de consumo electrico real. A 10 euros cada uno, son la forma mas rapida de automatizar cualquier aparato de casa con Alexa o Google.",
    longDesc:"Casi 9.000 valoraciones en Amazon y nota de 4.4. Los Tapo P110 hacen una cosa y la hacen bien: enchufas cualquier aparato y lo controlas por voz o programas por horario. La gracia esta en que miden el consumo real: descubres que la cafetera gasta 1.200W y el televisor en standby 8W al mes. La programacion horaria permite encender el calefactor 30 minutos antes de llegar a casa. Funcionan con Alexa y Google, la app Tapo es funcional aunque no la mas rapida del mundo.",
    pros:["Medicion de consumo electrico real en la app","Compatible Alexa + Google simultaneamente","Programacion horaria y temporizadores","10€ por enchufe en pack de 4"],
    cons:["Solo WiFi 2.4GHz","App Tapo algo lenta en cargar datos"],
    verdict:"La forma mas economica de automatizar el hogar. Cafetera, ventilador, lampara, calefactor. A 10€ el enchufe no hay excusa para no empezar.",
    amazonUrl:"https://www.amazon.es/dp/B09YL5GY1J?tag=digitalconect-21",
    metaTitle:"Tapo P110 Pack 4: Enchufes inteligentes por 10€ cada uno - Analisis 2026",
    metaDescription:"4 enchufes Tapo P110 por 39€. Medicion consumo, Alexa, Google. El pack imprescindible para hogar inteligente.",
  },
  {
    id:13, slug:"switchbot-curtain-3", name:"SwitchBot Curtain 3",
    category:"enchufes", rating:4.2, reviews:980, price:"69,99", oldPrice:"89,99",
    badge:"Innovador", badgeColor:"#8B5CF6", weeklyBest:false,
    image:"https://m.media-amazon.com/images/I/41LI8m5PCPL._AC_SL1500_.jpg",
    imageAlt:"SwitchBot Curtain 3 motor automatizacion cortinas compatible Alexa Google HomeKit",
    imageTitle:"SwitchBot Curtain 3 - Automatiza tus cortinas existentes sin cambiarlas",
    shortDesc:"Automatiza tus cortinas existentes sin cambiarlas. Se instala en 5 minutos, se abre con el sol y se cierra al anochecer. Compatible con Alexa, Google y Apple HomeKit.",
    longDesc:"De todos los dispositivos inteligentes que he probado, el SwitchBot Curtain 3 es el que mas impresiona a las visitas. Las cortinas se abren solas por la manana con el sol y se cierran al anochecer. La instalacion no lleva mas de 5 minutos, se sujeta al riel y no deja marca. El panel solar opcional elimina la necesidad de cargar la bateria. Funciona con Alexa, Google y HomeKit. El ruido es ligero pero se nota en habitaciones silenciosas. La bateria dura 4-6 meses sin panel solar.",
    pros:["Instalacion en 5 minutos sin herramientas","Panel solar opcional para carga perpetua","Triple compatibilidad Alexa + Google + HomeKit","Apertura y cierre por horario solar"],
    cons:["Ruido ligero al moverse","Bateria 4-6 meses sin panel solar"],
    verdict:"Automatizar las cortinas es un pequeno lujo que cambia la rutina matutina. Se instala sin obras, sin cambiar cortinas, y funciona con todo.",
    amazonUrl:"https://www.amazon.es/dp/B09V3KXJPB?tag=digitalconect-21",
    metaTitle:"SwitchBot Curtain 3: Cortinas automaticas por 70€ - Opinion 2026",
    metaDescription:"SwitchBot Curtain 3 por 69€. Automatiza cortinas existentes, panel solar, Alexa + Google + HomeKit. Instalacion en 5 minutos.",
  },
  {
    id:14, slug:"aqara-presence-sensor-fp2", name:"Aqara Presence Sensor FP2",
    category:"enchufes", rating:4.6, reviews:720, price:"54,99", oldPrice:"69,99",
    badge:"Sensor Premium", badgeColor:"#06B6D4", weeklyBest:false,
    image:"https://m.media-amazon.com/images/I/31Pm3gu1bBL._AC_SL1500_.jpg",
    imageAlt:"Aqara Presence Sensor FP2 sensor presencia mmWave deteccion estatica Apple HomeKit",
    imageTitle:"Aqara FP2 - Sensor de presencia mmWave para automatizaciones avanzadas",
    shortDesc:"Sensor mmWave de ultima generacion. Detecta si estas en la habitacion aunque estes sentado sin moverte. Define zonas dentro de la misma estancia para automatizaciones avanzadas.",
    longDesc:"Los sensores de movimiento clasicos tienen un problema: si te sientas quieto, te dan por ido y apagan la luz. El Aqara FP2 usa tecnologia mmWave (radar de ondas milimetricas) para detectar presencia, no movimiento. Sabe que estas ahi aunque estes leyendo en el sofa. Ademas permite definir hasta 5 zonas dentro de una habitacion, por ejemplo la mesa de trabajo y el sofa, con automatizaciones diferentes para cada zona. Compatible nativamente con Apple HomeKit. La configuracion no es trivial, requiere algo de paciencia.",
    pros:["Deteccion de presencia estatica con mmWave","Hasta 5 zonas por estancia","Apple HomeKit nativo sin hubs extra","Automatizaciones avanzadas por zona"],
    cons:["Requiere hub Aqara para funciones avanzadas","Configuracion inicial algo compleja"],
    verdict:"El sensor mas avanzado del mercado para automatizaciones inteligentes. Si quieres que las luces se enciendan cuando entras y se apaguen cuando sales de verdad, este es el camino.",
    amazonUrl:"https://www.amazon.es/dp/B0CDG3WKRL?tag=digitalconect-21",
    metaTitle:"Aqara FP2: El sensor de presencia que sabe que estas ahi (2026)",
    metaDescription:"Aqara Presence Sensor FP2 por 54€. Deteccion mmWave estatica, 5 zonas, HomeKit. El sensor mas avanzado del mercado.",
  },
  {
    id:15, slug:"tado-v3plus", name:"Tado Termostato V3+",
    category:"climatizacion", rating:4.3, reviews:2156, price:"199,99", oldPrice:"249,99",
    badge:"Ahorro Real", badgeColor:"#06B6D4", weeklyBest:false,
    image:"https://m.media-amazon.com/images/I/31GtT0VEETL._AC_SL1000_.jpg",
    imageAlt:"Tado termostato inteligente V3+ geolocalizacion ahorro calefaccion",
    imageTitle:"Tado V3+ - Termostato inteligente con geolocalizacion y ahorro real en calefaccion",
    shortDesc:"Termostato inteligente con geolocalizacion que baja la calefaccion cuando sales de casa y la sube antes de llegar. Compatible con el 95% de calderas en Espana. Ahorro real del 20-30%.",
    longDesc:"Un invierno completo con el Tado V3+ en Alicante, donde los inviernos son suaves pero la calefaccion se usa 3-4 meses. Los datos: ahorro del 23% en la factura de gas respecto al invierno anterior con el mismo uso de la casa. La geolocalizacion funciona bien, detecta que sales y baja la temperatura progresivamente, y la sube 20 minutos antes de que llegues. La instalacion manual tarda unos 30 minutos con las instrucciones de la app. Compatible con el 95% de calderas del mercado espanol. Las funciones avanzadas como deteccion de ventana abierta requieren suscripcion Auto-Assist.",
    pros:["Geolocalizacion automatica precisa","Compatible con 95% de calderas espanolas","Informes detallados de ahorro mensual","Se amortiza en un invierno"],
    cons:["Funciones avanzadas necesitan suscripcion Auto-Assist","Instalacion manual de 30 minutos"],
    verdict:"Se amortiza en un solo invierno. El ahorro del 20-30% en calefaccion esta respaldado por datos reales de uso en Alicante. La geolocalizacion es un lujo que deberia ser estandar.",
    amazonUrl:"https://www.amazon.es/dp/B07FZ3TXCQ?tag=digitalconect-21",
    metaTitle:"Tado V3+: Cuanto ahorras realmente? Datos de un invierno completo",
    metaDescription:"Tado V3+ por 199€. Datos reales: ahorro 23% en calefaccion. Geolocalizacion, compatible 95% calderas. Se amortiza en un invierno.",
  },
];

export const COMPARATIVES = [
  {
    slug:"mejores-robots-aspiradores",
    title:"Los 5 mejores robots aspiradores de 2026",
    subtitle:"Hemos probado los robots mas vendidos durante 3 meses en un piso de 120m2 con perro. Estas son nuestras conclusiones con datos reales de rendimiento.",
    category:"aspiradores",
    image:"https://m.media-amazon.com/images/I/71cihNMRF4L._AC_SL1500_.jpg",
    imageAlt:"Comparativa mejores robots aspiradores 2026 Roborock Dreame Xiaomi",
    tag:"Actualizado Mar 2026",
    items:[
      {pos:1,name:"Roborock S8 MaxV Ultra",score:9.4,price:"649€",best:"Mejor calidad global sin compromiso",productSlug:"roborock-s8-maxv-ultra",recommended:true},
      {pos:2,name:"Dreame L10s Ultra Gen 2",score:9.0,price:"373€",best:"Mejor relacion calidad-precio",productSlug:"dreame-l10s-ultra-gen2"},
      {pos:3,name:"Xiaomi Robot X10+",score:8.5,price:"329€",best:"Mejor ecosistema Xiaomi",productSlug:"xiaomi-robot-x10-plus"},
    ],
    metaTitle:"Mejores Robots Aspiradores 2026 - Comparativa tras 3 meses de pruebas reales",
    metaDescription:"Comparativa de robots aspiradores 2026 tras meses de pruebas en un piso real. Roborock S8 MaxV, Dreame L10s, Xiaomi X10+. Datos de succion, fregado y autonomia.",
  },
  {
    slug:"robots-aspiradores-fregado",
    title:"Robots con fregado: cual friega mejor de verdad?",
    subtitle:"Sonico vs vibratorio vs rotativo. Manchamos suelos a proposito con cafe, ketchup y pisadas para comprobar que sistema limpia mejor.",
    category:"aspiradores",
    image:"https://m.media-amazon.com/images/I/61gvoVh3u-L._AC_SL1200_.jpg",
    imageAlt:"Comparativa robots aspiradores con fregado sonico vs vibratorio 2026",
    tag:"Comparativa fregado",
    items:[
      {pos:1,name:"Roborock S8 MaxV Ultra",score:9.6,price:"649€",best:"Fregado sonico 4.000 vibraciones",productSlug:"roborock-s8-maxv-ultra",recommended:true},
      {pos:2,name:"Dreame L10s Ultra Gen 2",score:8.4,price:"373€",best:"Fregado por presion eficaz",productSlug:"dreame-l10s-ultra-gen2"},
    ],
    metaTitle:"Robots aspiradores con fregado 2026: sonico vs vibratorio vs rotativo",
    metaDescription:"Comparativa de fregado entre robots aspiradores. Probamos sonico, vibratorio y rotativo con manchas reales. Roborock vs Dreame.",
  },
  {
    slug:"termostatos-inteligentes",
    title:"Tado vs Netatmo vs Google Nest: termostatos inteligentes",
    subtitle:"Datos reales de un invierno completo en Alicante. Cuanto ahorra cada uno y cual se instala mas facil en calderas espanolas.",
    category:"climatizacion",
    image:"https://m.media-amazon.com/images/I/31GtT0VEETL._AC_SL1000_.jpg",
    imageAlt:"Comparativa termostatos inteligentes Tado Netatmo Google Nest ahorro calefaccion 2026",
    tag:"Datos reales de ahorro",
    items:[
      {pos:1,name:"Tado V3+",score:8.8,price:"199€",best:"Geolocalizacion mas precisa y ahorro 23%",productSlug:"tado-v3plus",recommended:true},
    ],
    metaTitle:"Termostatos inteligentes 2026: Tado vs Netatmo vs Nest - Datos de ahorro real",
    metaDescription:"Comparativa termostatos inteligentes con datos de un invierno en Alicante. Tado V3+ ahorro 23%. Cual instalar en tu caldera.",
  },
  {
    slug:"camaras-seguridad-baratas",
    title:"Camaras de seguridad por menos de 70 euros",
    subtitle:"Tapo vs Ring vs Reolink. Probamos en exterior con lluvia, interior con mascotas y de noche para ver cual graba mejor sin pagar suscripcion.",
    category:"seguridad",
    image:"https://m.media-amazon.com/images/I/61q2h25gFcL._AC_SL1500_.jpg",
    imageAlt:"Comparativa camaras seguridad baratas WiFi Tapo Ring Reolink 2026",
    tag:"Menos de 70€",
    items:[
      {pos:1,name:"TP-Link Tapo C320WS",score:9.0,price:"39€",best:"Exterior 2K sin suscripcion mensual",productSlug:"tapo-c320ws",recommended:true},
      {pos:2,name:"Ring Indoor Cam 2a Gen",score:8.2,price:"59€",best:"Interior con Alexa integrada",productSlug:"ring-indoor-cam"},
      {pos:3,name:"Reolink Argus 4 Pro",score:8.8,price:"129€",best:"Sin cables con panel solar",productSlug:"reolink-argus-4-pro"},
    ],
    metaTitle:"Mejores camaras seguridad baratas 2026 - Comparativa sin suscripcion",
    metaDescription:"Camaras de seguridad WiFi por menos de 70€. Tapo C320WS, Ring Indoor, Reolink Argus. Interior y exterior sin suscripcion.",
  },
];

export const GUIAS = [
  {
    slug:"domotica-principiantes",
    title:"Domotica para principiantes: por donde empiezo?",
    excerpt:"La guia que me hubiera gustado leer antes de gastar 200 euros en cosas que no necesitaba. Paso a paso real, sin tecnicismos y con los errores que deberias evitar.",
    image:"https://m.media-amazon.com/images/I/71xoR4A7xvL._AC_SL1000_.jpg",
    imageAlt:"Guia domotica principiantes hogar inteligente paso a paso 2026",
    readTime:"15 min",
    content:"Cuando empece con la domotica, me fui directo a comprar bombillas inteligentes sin tener ni idea de ecosistemas. Error numero uno. Acabe con bombillas WiFi que no hablaban con el altavoz y un cabreo considerable.\n\nLo primero que tienes que decidir es tu ecosistema: Alexa (Amazon), Google Home o Apple HomeKit. Mi recomendacion si empiezas de cero: Alexa. Tiene mas dispositivos compatibles, los precios son mejores y las rutinas de automatizacion son mas flexibles.\n\nSegundo paso: compra un Echo Dot 5 por 30€. Es el cerebro. Sin el, los dispositivos inteligentes son enchufes caros con app.\n\nTercer paso: no compres todo a la vez. Empieza por un enchufe inteligente Tapo P110 (10€ la unidad) para la lampara del salon. Configura una rutina \"Alexa, buenas noches\" que apague esa lampara. Cuando notes que funciona y te gusta, expandes.\n\nCuarto paso: iluminacion. Aqui la decision es Philips Hue (mejor calidad, mas caro) o Tapo L530E (10€ la bombilla, calidad suficiente). Si quieres probar sin arriesgarte, Tapo. Si quieres el mejor resultado, Hue.\n\nQuinto paso: seguridad si la necesitas. Una Tapo C320WS por 40€ para exterior y ya tienes camara sin suscripcion.\n\nPresupuesto total para empezar: entre 95€ (Echo Dot + enchufe) y 200€ (Dot + enchufes + bombillas + camara). Con eso ya tienes un hogar inteligente funcional.",
    ctas:[{text:"Echo Dot 5 - 54,99€",url:"https://www.amazon.es/dp/B09B8X9RGM?tag=digitalconect-21"},{text:"Tapo P110 Pack 4 - 39,99€",url:"https://www.amazon.es/dp/B09YL5GY1J?tag=digitalconect-21"}],
    metaTitle:"Domotica para principiantes 2026: guia paso a paso desde cero",
    metaDescription:"Guia de inicio en domotica sin tecnicismos. Que comprar primero, que ecosistema elegir, errores a evitar. Empieza desde 40€.",
  },
  {
    slug:"guia-iluminacion-inteligente",
    title:"Guia completa de iluminacion inteligente 2026",
    excerpt:"Philips Hue vs TP-Link Tapo vs IKEA Dirigera vs Yeelight. Precios, ecosistemas, calidad de color y que comprar segun tu presupuesto.",
    image:"https://m.media-amazon.com/images/I/61DUO0NqyyL._AC_SL1500_.jpg",
    imageAlt:"Guia iluminacion inteligente bombillas WiFi Philips Hue vs Tapo vs IKEA 2026",
    readTime:"12 min",
    content:"La iluminacion inteligente es probablemente el primer paso visible en domotica. Llegas a casa, dices \"Alexa, buenas tardes\" y el salon se enciende con un tono calido. Suena a ciencia ficcion, pero cuesta 10€.\n\nLas opciones principales en Espana en 2026 son cuatro: Philips Hue, TP-Link Tapo, IKEA Dirigera y Yeelight.\n\nPhilips Hue es el rey indiscutible. Colores precisos, transiciones suaves, ecosistema maduro con cientos de escenas, y compatible con todo: Alexa, Google, HomeKit. El starter kit por 90€ incluye bridge y 3 bombillas. La pega: cada bombilla extra cuesta 25-40€.\n\nTP-Link Tapo L530E es el rival presupuesto. 10€ por bombilla, WiFi directo sin hub. Los colores son correctos pero los blancos calidos no llegan a la calidad de Hue. Para empezar a probar, perfecto.\n\nIKEA Dirigera ha mejorado mucho. El hub cuesta 70€ y las bombillas 10-15€. La app IKEA Home Smart es funcional. Compatible con Alexa y Google. Buena opcion intermedia.\n\nYeelight tiene buenas tiras LED pero su ecosistema en Espana es limitado.\n\nMi recomendacion: si el presupuesto es clave, Tapo. Si quieres calidad y durabilidad, Hue. Si ya compras en IKEA, Dirigera puede tener sentido.",
    ctas:[{text:"Philips Hue Starter Kit - 89,99€",url:"https://www.amazon.es/dp/B07QV9XB87?tag=digitalconect-21"},{text:"Tapo L530E Pack 2 - 19,99€",url:"https://www.amazon.es/dp/B07V47FMJM?tag=digitalconect-21"}],
    metaTitle:"Iluminacion inteligente 2026: Hue vs Tapo vs IKEA - Guia definitiva",
    metaDescription:"Comparativa bombillas inteligentes. Philips Hue vs Tapo vs IKEA Dirigera. Precios, calidad color, ecosistemas. Que comprar segun presupuesto.",
  },
  {
    slug:"guia-enchufes-inteligentes",
    title:"Enchufes inteligentes: cuales comprar y para que sirven",
    excerpt:"Medir consumo electrico, programar horarios, automatizar aparatos viejos. Todo lo que necesitas saber sobre enchufes WiFi en 2026.",
    image:"https://m.media-amazon.com/images/I/51k2064fHRL._AC_SL1000_.jpg",
    imageAlt:"Guia enchufes inteligentes WiFi Tapo P110 medicion consumo 2026",
    readTime:"8 min",
    content:"Un enchufe inteligente cuesta 10€ y convierte cualquier aparato tonto en uno smart. Cafetera, ventilador, lampara de pie, calefactor, deshumidificador. Lo que sea que se encienda con un interruptor fisico.\n\nLos Tapo P110 de TP-Link son los que recomiendo. Por 40€ tienes un pack de 4 con medicion de consumo real. Enchufas la cafetera, abres la app y ves que gasta 1.200W al preparar cafe y 0,5W en standby.\n\nPara que los uso yo:\n\nCafetera: se enciende sola a las 7:00 de lunes a viernes. Llego a la cocina y el cafe esta listo.\n\nVentilador del dormitorio: se apaga a las 3:00 AM cuando baja la temperatura. Ahorro en electricidad y no me despierto helado.\n\nLampara de pie del salon: conectada a la rutina \"Alexa, buenas noches\". Se apaga sola.\n\nCalefactor del bano: se enciende 15 minutos antes de la alarma. Llego al bano y ya esta caliente.\n\nEl consumo real que miden los Tapo P110 es muy util para detectar electrodomesticos que gastan demasiado en standby. Mi television antigua consumia 12W apagada. 12W * 24h * 365 dias = 105 kWh al ano. A 0,15€/kWh son 16€ tirados.\n\nAlternativas: los Meross cuestan un poco mas pero tienen compatibilidad HomeKit. Los Shelly son para usuarios avanzados que quieran integracion con Home Assistant.",
    ctas:[{text:"Tapo P110 Pack 4 - 39,99€",url:"https://www.amazon.es/dp/B09YL5GY1J?tag=digitalconect-21"}],
    metaTitle:"Enchufes inteligentes 2026: cuales comprar y para que sirven realmente",
    metaDescription:"Guia de enchufes WiFi. Tapo P110 por 10€ cada uno. Medicion consumo, automatizaciones, ahorro. Para que usarlos y cuales comprar.",
  },
  {
    slug:"como-elegir-camara-seguridad",
    title:"Como elegir tu camara de seguridad WiFi en 2026",
    excerpt:"Interior o exterior, con cable o bateria, con o sin suscripcion. Lo que tienes que saber antes de comprar y los errores que comete todo el mundo.",
    image:"https://m.media-amazon.com/images/I/61kJ6yFdsCL._AC_SL1500_.jpg",
    imageAlt:"Guia como elegir camara seguridad WiFi interior exterior sin suscripcion 2026",
    readTime:"10 min",
    content:"Lo primero: donde la vas a poner? Interior o exterior cambia todo.\n\nExterior necesita IP66 (resistente a lluvia), vision nocturna potente y resolucion minima 2K para ver detalles a distancia. La Tapo C320WS por 40€ cumple todo esto. Si no llega cable de corriente, Reolink Argus 4 Pro con panel solar por 130€.\n\nInterior es mas sencillo. La Ring Indoor Cam por 60€ funciona perfecto si tienes Alexa. Si no usas Alexa, una Tapo C200 por 25€ basta.\n\nSegundo tema critico: suscripcion. Muchas camaras te obligan a pagar 3-5€ al mes para guardar grabaciones. Las Tapo graban en MicroSD gratis. Las Ring necesitan Ring Protect (3,99€/mes) para guardar videos. Las Reolink tambien graban en tarjeta gratis.\n\nTercer punto: deteccion de movimiento. Las camaras baratas te mandan 40 notificaciones al dia. Sombras, gatos, coches pasando. Las buenas distinguen personas de animales. La Tapo C320WS lo hace bien. La Ring tambien.\n\nCuarto: campo de vision. Busca minimo 110 grados. Menos que eso y te dejan angulos muertos.\n\nResumen rapido: exterior sin suscripcion, Tapo C320WS (39€). Interior con Alexa, Ring Indoor (59€). Sin cables, Reolink Argus 4 Pro (129€).",
    ctas:[{text:"Tapo C320WS - 39,99€",url:"https://www.amazon.es/dp/B09JFK81S7?tag=digitalconect-21"},{text:"Ring Indoor Cam - 59,99€",url:"https://www.amazon.es/dp/B0BFJNKJNZ?tag=digitalconect-21"},{text:"Reolink Argus 4 Pro - 129,99€",url:"https://www.amazon.es/dp/B0BXFQ3Z8D?tag=digitalconect-21"}],
    metaTitle:"Como elegir camara seguridad WiFi 2026: guia sin suscripcion",
    metaDescription:"Guia para elegir camara de seguridad WiFi. Interior, exterior, con o sin cables, sin suscripcion. Tapo, Ring, Reolink comparadas.",
  },
];

export const BLOG_POSTS = [
  {
    slug:"alexa-vs-google-home-2026",
    title:"Alexa vs Google Home en 2026: cual conviene mas",
    excerpt:"Tras 6 meses con ambos ecosistemas en la misma casa, las diferencias que importan de verdad y cual recomiendo segun tu situacion.",
    date:"2026-02-26", readTime:"8 min",
    tag:"Comparativa", tagColor:"#10B981",
    image:"https://m.media-amazon.com/images/I/71xoR4A7xvL._AC_SL1000_.jpg",
    imageAlt:"Comparativa Alexa vs Google Home ecosistemas altavoces inteligentes 2026",
    content:"Llevo seis meses con un Echo Dot en la cocina y un Google Nest Hub en el salon. No ha sido un experimento cientifico, pero si lo bastante largo como para notar donde falla cada uno.\n\nLa primera diferencia real: Alexa entiende mejor el contexto en castellano. \"Alexa, pon la lista de la compra\" funciona siempre. Google a veces necesita la frase exacta o se lia con variaciones.\n\nDonde Google gana con diferencia es en respuestas informativas. Preguntas tipo \"que diferencia hay entre LED y OLED\" y te da una respuesta decente. Alexa te lee el primer resultado de Bing, que no siempre es el mejor.\n\nEn domotica, ambos controlan luces y enchufes sin problemas. Pero las rutinas de Alexa son claramente mas flexibles. Puedes encadenar acciones con condiciones de hora, temperatura, dia de la semana. En Google Home configurar algo similar cuesta el doble de pasos.\n\nLa musica: si tienes Spotify, los dos funcionan bien. Con Amazon Music Unlimited tienes mejor integracion en Alexa, logicamente. YouTube Music va mejor en Google.\n\nMi conclusion despues de medio ano: si quieres domotica seria con muchos dispositivos, Alexa. Si tu prioridad es un asistente que responda bien y usas Android, Google. Si puedes, compra un Echo Dot por 30€ y prueba antes de invertir mas.",
    ctas:[
      {text:"Ver Echo Dot 5 - 54,99€",url:"https://www.amazon.es/dp/B09B8X9RGM?tag=digitalconect-21"},
      {text:"Ver Echo Show 8 - 154,99€",url:"https://www.amazon.es/dp/B0BLS3Y632?tag=digitalconect-21"},
    ],
    metaTitle:"Alexa vs Google Home 2026: comparativa real tras 6 meses de uso",
    metaDescription:"6 meses con Alexa y Google Home en la misma casa. Diferencias en domotica, musica, respuestas y rutinas. Cual elegir en Espana.",
  },
  {
    slug:"como-montar-hogar-inteligente-barato",
    title:"Monte un hogar inteligente por menos de 200 euros y asi quedo",
    excerpt:"Sin ser tecnico y gastando lo justo. Paso a paso real con los productos exactos, los errores que cometi y lo que habria hecho diferente.",
    date:"2026-02-22", readTime:"11 min",
    tag:"Guia practica", tagColor:"#F97316",
    image:"https://m.media-amazon.com/images/I/51k2064fHRL._AC_SL1000_.jpg",
    imageAlt:"Guia montar hogar inteligente barato por 150 euros paso a paso 2026",
    content:"No necesitas gastar 500 euros para tener un hogar inteligente funcional. Con menos de 200 tienes de sobra, y me consta porque lo hice.\n\nAntes de gastar un euro, decide ecosistema: Alexa o Google. No mezcles, al menos al principio. Mi recomendacion: Alexa. Mas dispositivos compatibles, precios mas agresivos y rutinas de automatizacion mas potentes.\n\nPrimera compra: Echo Dot 5a generacion, unos 55€ (baja a 30€ en ofertas). Es el cerebro de todo. Sin un altavoz inteligente, lo demas son gadgets caros con app.\n\nSegunda compra: pack de 4 enchufes TP-Link Tapo P110, 40€. Con estos automatizas cafetera (cafe listo al despertar), ventilador (se apaga a las 3AM), lampara de pie (rutina buenas noches) y lo que quieras. Miden consumo real, asi que descubres que electrodomesticos gastan de mas.\n\nTercera compra: Philips Hue Starter Kit, 90€. Si, es la compra mas cara. Pero las 3 bombillas con Bridge te dan 16 millones de colores y compatibilidad total. Puedes sustituir por 2 packs de Tapo L530E (40€) si el presupuesto manda.\n\nTotal: unos 185€ con Hue o 135€ con Tapo. Ya puedes decir \"Alexa, buenas noches\" y que se apague todo el salon. Ese momento, la primera vez que funciona, justifica cada euro.",
    ctas:[
      {text:"Echo Dot 5 - 54,99€",url:"https://www.amazon.es/dp/B09B8X9RGM?tag=digitalconect-21"},
      {text:"Tapo P110 Pack 4 - 39,99€",url:"https://www.amazon.es/dp/B09YL5GY1J?tag=digitalconect-21"},
      {text:"Philips Hue Starter - 89,99€",url:"https://www.amazon.es/dp/B07QV9XB87?tag=digitalconect-21"},
    ],
    metaTitle:"Hogar inteligente por menos de 200€: paso a paso con productos exactos (2026)",
    metaDescription:"Montar hogar inteligente desde 135€. Echo Dot + Tapo P110 + Philips Hue. Paso a paso real sin ser tecnico.",
  },
  {
    slug:"camara-vigilancia-exterior-sin-suscripcion",
    title:"Queria vigilar mi entrada sin pagar 5 euros al mes",
    excerpt:"Vivo en planta baja. Despues de un robo cercano decidi poner camara. El problema que descubres tarde con la mayoria de camaras baratas.",
    date:"2026-02-18", readTime:"8 min",
    tag:"Experiencia real", tagColor:"#8B5CF6",
    image:"https://m.media-amazon.com/images/I/61q2h25gFcL._AC_SL1500_.jpg",
    imageAlt:"Camara vigilancia exterior sin suscripcion Tapo C320WS experiencia real 2026",
    content:"Vivo en planta baja con jardin en Alicante. Despues de un robo en el portal de al lado, decidi poner una camara en la entrada. Mi requisito principal: sin pagar suscripcion mensual.\n\nEl 80% de camaras baratas tienen un problema que descubres a las dos semanas: la deteccion de movimiento es tan mala que recibes 40 notificaciones al dia. Sombras de arboles, gatos callejeros, hojas que caen, coches pasando. Te acostumbras a ignorar las alertas, que es justo lo contrario de lo que quieres.\n\nDespues de probar tres camaras, mi conclusion:\n\nLa Tapo C320WS gana de lejos por 40€. Graba en 2K real, la vision nocturna a color funciona gracias a un foco LED integrado, y la deteccion distingue personas de animales. Graba en tarjeta MicroSD, cero euros al mes de suscripcion. Lleva un ano en mi entrada y sigue funcionando perfecto.\n\nPara interior, la Ring Indoor Cam por 60€ es buena opcion si tienes Alexa. \"Alexa, ensenameame la entrada\" y la ves en el Echo Show. Pero necesitas Ring Protect (3,99€/mes) para guardar grabaciones.\n\nSi no llega cable de corriente a donde necesitas la camara, Reolink Argus 4 Pro con panel solar por 130€. Es cara pero es la unica inalambrica seria en 4K.\n\nResumen: exterior sin suscripcion, Tapo C320WS sin dudarlo.",
    ctas:[
      {text:"Tapo C320WS - 39,99€",url:"https://www.amazon.es/dp/B09JFK81S7?tag=digitalconect-21"},
      {text:"Ring Indoor Cam - 59,99€",url:"https://www.amazon.es/dp/B0BFJNKJNZ?tag=digitalconect-21"},
    ],
    metaTitle:"Camara vigilancia exterior sin suscripcion: mi experiencia real (2026)",
    metaDescription:"Vivo en planta baja. Probe 3 camaras y me quede con la Tapo C320WS por 39€. 2K, sin suscripcion, un ano de uso.",
  },
];

export function getProductBySlug(slug) { return PRODUCTS.find(p => p.slug === slug) || null; }
export function getProductsByCategory(catId) { return PRODUCTS.filter(p => p.category === catId); }
export function getCategoryBySlug(slug) { return CATEGORIES.find(c => c.slug === slug) || null; }
export function getBlogBySlug(slug) { return BLOG_POSTS.find(p => p.slug === slug) || null; }
export function getComparativeBySlug(slug) { return COMPARATIVES.find(c => c.slug === slug) || null; }

// Extraer ASIN de URL de Amazon
export function extractASIN(urlOrAsin) {
  if (!urlOrAsin) return null;
  if (/^[A-Z0-9]{10}$/.test(urlOrAsin)) return urlOrAsin;
  const match = urlOrAsin.match(/\/(?:dp|gp\/product)\/([A-Z0-9]{10})/);
  return match ? match[1] : null;
}

export function getAmazonUrl(url) {
  if (!url) return "#";
  if (url.includes("tag=")) return url;
  return url + (url.includes("?") ? "&" : "?") + "tag=" + SITE_CONFIG.amazonTag;
}
